_wandb:
    value:
        cli_version: 0.20.1
        code_path: code/weave_koala/koala_weave.py
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "3":
                - 55
            "4": 3.12.0
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
